### ISSUE TITLE
[Feature] Parameterise the docker image version in the YAML file

### ISSUE THREAD

**Issue by rockyhmchen** [rockyhmchen/XunitK8s#1]
Parameterise the docker image version in the YAML file

e.g.
```
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata: 
    name: someservice
  spec: 
    template: 
      metadata: 
        labels: 
          component: someservice
      spec: 
        containers: 
          - name: someservice
            image: docker.images.io/someservice:${docker.someservice.version}
...
```
